frequency: 30

two_d_mode: true

publish_tf: true

map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: odom

odom0: {odom topic}
odom0_config: [false, false, false, 
              false, false, true,
              true, true, false,
              false, false, true
              false, false, false]  
odom_differential: false

imu0: {odom topic}
imu0_config: [false, false, false, 
              false, false, true,
              false, false, false,
              false, false, true
              true, false, false]  
imu_differential: false
